server:
  port: 8001
spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: product
          uri: lb://product
          predicates:
            - Path=/product/**
        - id: cart
          uri: lb://cart
          predicates:
            - Path=/cart/**
        - id: database
          uri: lb://database
          predicates:
            - Path=/database/**
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**

  main:
    web-application-type: reactive
eureka:
  instance:
    instance-id: gateway
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8000/eureka